p8105_hw2_hs3393
================
Haochen Sun
2022-09-28

### Import packages

``` r
library(readr)
library(tidyverse)
library(readxl)
```

# Problem 1

``` r
data <- read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names()
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
clean_data <-   select(data, line, station_name, station_latitude,
         station_longitude, route1:route11, entry, 
         vending, entrance_type, ada)  %>% 
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))

head(data, n = 5)
```

    ## # A tibble: 5 × 32
    ##   division line     station…¹ stati…² stati…³ route1 route2 route3 route4 route5
    ##   <chr>    <chr>    <chr>       <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 2 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 3 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 4 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 5 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## # … with 22 more variables: route6 <chr>, route7 <chr>, route8 <dbl>,
    ## #   route9 <dbl>, route10 <dbl>, route11 <dbl>, entrance_type <chr>,
    ## #   entry <chr>, exit_only <chr>, vending <chr>, staffing <chr>,
    ## #   staff_hours <chr>, ada <lgl>, ada_notes <chr>, free_crossover <lgl>,
    ## #   north_south_street <chr>, east_west_street <chr>, corner <chr>,
    ## #   entrance_latitude <dbl>, entrance_longitude <dbl>, station_location <chr>,
    ## #   entrance_location <chr>, and abbreviated variable names ¹​station_name, …

This dataset describes the subway lines in New York, and the stations
along each line. The data set also includes the latitude and longitude
of each station. Route 1-11 means that which route of subway you can
take in this station. Whether the entrance is an entry, whther there is
a ticket vending machine, and whether it is ADA accessible. Also, the
dataset specified the entrance type of each station (stair, elevator,
door, or other type, 7 types in total). The other information include
the division, whether the entry have staffs and their staff hour,
whether there are free crossover, the streets surrounding, the entrance
is at which corner, the entrance location, logitude and latitude.

To clean the data, I selected 19 variables from the original dataset,
change the names to be well formatted, and I converted the entry
varaible from yes/no to True/False. The data is not tidy, because the
route information can be integrated.

### Numerical properties

``` r
station <- nrow(distinct(clean_data, station_name, line))
print(station)
```

    ## [1] 465

``` r
ada_num <- nrow(select(clean_data, station_name, line, ada)%>% 
                   unique() %>% 
                   filter(ada == T) )
print(ada_num)
```

    ## [1] 84

``` r
allow_ent <- filter(clean_data, vending == "NO" ) %>% pull(entry)
proportion <- round( sum(allow_ent)/length(allow_ent), digits = 3 )
print(proportion)
```

    ## [1] 0.377

Therefore, there are 465 distinct stations. 183 stations are ADA
compliant. 37.70% station entrances/exits without vending allow
entrance.

## Reformat the data

``` r
# change the data type of some route, otherwise they cannot be merged
col_name <- c("route8", "route9", "route10", "route11")
clean_data[col_name] <- sapply(clean_data[col_name], as.character)

A_train <- pivot_longer(clean_data, cols = route1:route11, 
    names_to = "route_number", names_prefix = "route", 
    values_to = "route_name", values_drop_na = T) %>% 
  distinct(station_name, line, .keep_all = T ) %>% 
  filter(route_name == "A")

print(nrow(A_train))
```

    ## [1] 60

``` r
print(nrow
      (filter(A_train, ada == T))
      )
```

    ## [1] 17

Therefore, there are 60 stations that serves A train, and 17 of them are
ADA compliant.

# Problem 2

``` r
# The mutate function will indicate which sheet is from

trash_data <- read_excel("data/Trash Wheel Collection Data.xlsx", 
        sheet ="Mr. Trash Wheel", range = "A2:N549") %>%
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls, sports_balls = as.integer(round(sports_balls, digits = 0))) %>% 
  mutate(group = 1 ) %>% 
  mutate(year = as.numeric(year))

prof_data <- read_excel("data/Trash Wheel Collection Data.xlsx",
        sheet ="Professor Trash Wheel", range = "A2:M96") %>%
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(group = 2)

merge_data <- bind_rows(trash_data, prof_data)
```

There are 641 observations in the whole dataset, recording the dumpter
number, date of collection, weight (whose mean is 3.0241498 and SD is
0.8436163. The volume of litter (whose mean is 15.2199688 cubic yards
and SD is 1.4448099 cubic yards). The amount of different types of
litter, including plastic bottle, polystyrene, cigarette butt, glass
bottle, grocery bag, chip bag and sport ball in every single dumpster.
Also, the dataset provides the information of how many homes these
litters have powered. The data is originated from two wheels, the number
of group 1 indicates Mr.Trash Wheel. and 2 indicates Professor Trash
Wheel.

For example, the Dumpster 1 on the Mr.Trash wheel by the day of 5/16,
collected 4.31 tons, 18 cubic yards of litter. It includes 1,450 plastic
bottles, 1,820 polystyre, 126,000 cigarette butts, 72 glass bottles, 584
grocery bags, 1162 chip bags and 7 sports balls.

## Numeric properties

``` r
total <- filter(merge_data, group == "2") %>%
  pull(weight_tons)


ball <- filter(merge_data , group == "1"& year == "2020") %>% 
  pull(sports_balls)
```

Therefore, the total weight of trash collected by Professor Trash Wheel
is 190.12 tons. The total number of sports balls collected by Mr.Trash
Wheel in 2020 is 856.

# Problem 3

``` r
pol <- read_csv("data/pols-month.csv") %>%
  janitor::clean_names()%>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = recode( month, "01" = "Jan", "02" = "Feb", "03" = "Mar", "04" = "Apr", "05" = "May", 
    "06" = "Jun", "07" = "Jul", "08" = "Aug", "09" = "Sep", "10" = "Oct", "11" = "Nov", "12" = "Dec")) %>% 
  mutate(president = recode(prez_dem, `0` = "gop", `1` = "dem")) %>% 
  select(c(-prez_gop, -prez_dem, -day))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp <- read_csv("data/snp.csv") %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(month = recode( month, "1" = "Jan", "2" = "Feb", "3" = "Mar", "4" = "Apr", "5" = "May", "6" = "Jun", "7" = "Jul", "8" = "Aug", "9" = "Sep", "10" = "Oct", "11" = "Nov", "12" = "Dec")) %>%
  select(-day) %>%
  mutate(year = as.numeric(year)) %>% 
  mutate(year = if_else(year < 35, true = year + 2000, false = year + 1900)) %>% 
  mutate(year = as.character(year)) %>%
  arrange(year, month) %>% 
  relocate(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemploy <- read_csv("data/unemployment.csv") %>%
  pivot_longer(Jan:Dec, names_to = "month", values_to = "number_umemploy") %>%
  janitor::clean_names() %>% 
  mutate(year = as.character(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
merge_data <- left_join(pol, snp) %>% 
  left_join(unemploy) 
```

    ## Joining, by = c("year", "month")
    ## Joining, by = c("year", "month")

The dataset pol shows at each year, each month, the party of the
president belongs to. As well as the governor number, the senator
number, representative number of the two parties. The dataset snp
includes the closing values of the S&P stock index on the associate
date, and the data set unemploy shows percentage of unemployed on the
associate date. For the “2” in the prez_dom column, it is treated as “1”
after checking the president history.

The dimension of the merged dataset is 822 \* 11. The range of year is
1947 to 2015. The names of variable is year, month, gov_gop, sen_gop,
rep_gop, gov_dem, sen_dem, rep_dem, president, close, number_umemploy.
